In [1]:
import tensorflow as tf
import numpy

# Create two random matrices for matrix multiplication
A = tf.random.normal([3, 3])  # 3x3 matrix
B = tf.random.normal([3, 3])  # 3x3 matrix

# Perform matrix multiplication
C = tf.matmul(A, B)

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = tf.linalg.eigh(C)

# Print the results
print("Matrix A:")
print(A.numpy())
print("\nMatrix B:")
print(B.numpy())
print("\nMatrix C (A * B):")
print(C.numpy())

print("\nEigenvalues of matrix C:")
print(eigenvalues.numpy())

print("\nEigenvectors of matrix C:")
print(eigenvectors.numpy())


Matrix A:
[[ 0.04308302  0.5654639  -0.3199596 ]
 [-1.1082838   0.9970972   0.19860204]
 [ 1.5333116  -1.2748919  -0.64154565]]

Matrix B:
[[-0.96308005  0.299498    1.8905128 ]
 [ 1.5395595   0.02200339 -0.7530315 ]
 [-0.30789945  1.9073709  -1.7807994 ]]

Matrix C (A * B):
[[ 0.9275883  -0.58493626  0.22542076]
 [ 2.5413072   0.0688185  -3.1997406 ]
 [-3.2419422  -0.7924937   5.001243  ]]

Eigenvalues of matrix C:
[-2.4576228  1.1224148  7.332855 ]

Eigenvectors of matrix C:
[[-0.7209161  -0.46049502  0.51790357]
 [ 0.6484817  -0.71183217  0.26975262]
 [-0.24444072 -0.53032005 -0.81179374]]
